export const DEFAULT_MAX_EXTRA_TESTS_PERCENT = 50;
export const DEFAULT_MAX_EXTRA_TESTS_PERCENT_FOR_SMALL_TEST_AMOUNT = 100;
export const SMALL_TEST_AMOUNT_THRESHOLD = 3;
export const DEFAULT_MIN_MATCHED_TESTS_PERCENT = 50;
export const MATCH_RESULTS_COUNT = 5;
